### PR TITLE
Write "schwoabm" the correct™ way

### PR DESCRIPTION
**Pull request by knittl**
Everybody knows that verbs ending with the letter m are the best verbs.

### CODE REVIEW

**Review by SydoxX — APPROVED** [review]
How could we miss that? D:

**Comment by SydoxX** [comment]
Thanks for all the fixes!

**Comment by knittl** [comment]
I just noticed that th verb ended up with a different spelling in the final commit somehow. Intentionally or was this an accident? Cheers

**Comment by SydoxX** [comment]
Good eye, wasn't intentional, sorry. Got time to fix it? Else I'll take a look myself later.

Cheers

**Comment by knittl** [comment]
Glad to help. There you go: #4

**Pull request merged**
